Create post homepage
JoshMagnotta/NinerCreations pull request #16
Opened 2024-11-18 05:05 UTC by Kyle202034

Added in add post button along with edit and delete for the post if you created them
Added in Join/Leave buttons for the post and if you are the owner it says "Edit Post" There is also a button to reset the recent activity if you are the owner
Comments can be removed by user who made it or the owner of the post
Active Members are working and showing in the post with the owner being gold and other users being green
Created new templates for the create/edit/delete post functions along with new methods in the views.py for each of these
New urls.py have been added for each of these new functions
New css has been made mostly for the new buttons that are being shown.

2024-11-18 17:45 UTC, JoshMagnotta commented
![image](https://github.com/user-attachments/assets/bcada334-e2f1-4704-bbcf-9a6f0ee98904) - Add post button visible when not logged in, shouldn't be visible
![image](https://github.com/user-attachments/assets/3e9758a2-1b07-43bc-a0d6-70b953db5b43) - Remove bullet points on Active Members, fix edit button size, fix clear recent activity color, recent activity needs work
![image](https://github.com/user-attachments/assets/ed504342-f9f6-4b18-8783-53bccbb8968e) - Join button visible when not logged in (shouldn't be visible), errors when a non logged in user clicks join button
![image](https://github.com/user-attachments/assets/8c86b409-c7b3-4265-98bb-307e9e710d1d) - Active members show no members have joined when only the host has joined
When deleting a project, add a confirmation popup before actually deleting it

2024-11-18 17:45 UTC, JoshMagnotta requested changes
see comments

2024-11-24 11:31 UTC, Kyle202034 commented
All should now be updated properly please try to break it and let me know!

2024-12-02 19:03 UTC, JoshMagnotta approved these changes

2024-12-02 19:03 UTC, merged